# Generated by Django 5.2.3 on 2025-07-03 05:22

import IDMSapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IDMSapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Upload a profile picture (JPG, PNG, GIF supported)', null=True, upload_to=IDMSapp.models.user_profile_image_path),
        ),
    ]
