# Generated by Django 5.2.3 on 2025-06-25 18:58

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IDMSapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CronJobLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(help_text='Name of the scheduled job', max_length=100)),
                ('job_type', models.CharField(choices=[('DISEASE_ALERT', 'Disease Surveillance Alert'), ('SYMPTOM_ANALYSIS', 'Symptom Pattern Analysis'), ('EMERGENCY_CLEANUP', 'Emergency Request Cleanup'), ('APPOINTMENT_REMINDER', 'Appointment Reminders'), ('PREVENTION_CAMPAIGN', 'Prevention Campaign Updates'), ('DATA_BACKUP', 'Database Backup'), ('HEALTH_CHECK', 'System Health Check'), ('USER_CLEANUP', 'Inactive User Cleanup'), ('NOTIFICATION_QUEUE', 'Notification Queue Processing'), ('ANALYTICS_REPORT', 'Analytics Report Generation')], help_text='Category of the scheduled job', max_length=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='When the job started executing')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the job finished (success or failure)', null=True)),
                ('status', models.CharField(choices=[('S', 'Started'), ('C', 'Completed'), ('F', 'Failed'), ('T', 'Timeout')], default='S', help_text='Current status of the job', max_length=1)),
                ('duration_seconds', models.FloatField(blank=True, help_text='How long the job took to complete', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('records_processed', models.PositiveIntegerField(default=0, help_text='Number of records/items processed')),
                ('error_message', models.TextField(blank=True, help_text='Error details if job failed')),
                ('parameters', models.JSONField(blank=True, default=dict, help_text='Job parameters and configuration')),
                ('result_summary', models.JSONField(blank=True, default=dict, help_text='Summary of job execution results')),
                ('server_hostname', models.CharField(blank=True, help_text='Server that executed the job', max_length=100)),
                ('memory_usage_mb', models.PositiveIntegerField(blank=True, help_text='Peak memory usage during execution', null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['job_type', '-timestamp'], name='IDMSapp_cro_job_typ_1bbeb0_idx'), models.Index(fields=['status', '-timestamp'], name='IDMSapp_cro_status_c6a696_idx'), models.Index(fields=['-timestamp'], name='IDMSapp_cro_timesta_75731b_idx')],
            },
        ),
    ]
