# Generated by Django 5.2.3 on 2025-06-25 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IDMSapp', '0002_cronjoblog'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='can_self_register',
            field=models.BooleanField(default=False),
        ),
    ]
