# Generated by Django 5.2.3 on 2025-06-27 05:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IDMSapp', '0003_role_can_self_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('gps_coordinates', models.CharField(blank=True, max_length=50)),
                ('is_public', models.BooleanField(default=True)),
                ('services', models.JSONField(default=list, help_text='List of medical services offered')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff', models.ManyToManyField(limit_choices_to={'role__name__in': ['Doctor', 'Nurse']}, related_name='clinics', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
