# Generated by Django 5.2.3 on 2025-07-04 21:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IDMSapp', '0003_doctorschedule_alter_appointment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emergencyambulancerequest',
            options={'ordering': ['-request_time']},
        ),
        migrations.AddField(
            model_name='emergencyambulancerequest',
            name='additional_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='emergencyambulancerequest',
            name='approval_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='emergencyambulancerequest',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='emergencyambulancerequest',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emergencyambulancerequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_emergency_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emergencyambulancerequest',
            name='arrived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emergencyambulancerequest',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='IDMSapp.clinic'),
        ),
        migrations.AddField(
            model_name='emergencyambulancerequest',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emergencyambulancerequest',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_emergency_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emergencyambulancerequest',
            name='dispatched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emergencyambulancerequest',
            name='dispatched_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatched_emergency_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emergencyambulancerequest',
            name='in_transit_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emergencyambulancerequest',
            name='priority_override',
            field=models.CharField(blank=True, choices=[('critical', 'Critical'), ('urgent', 'Urgent'), ('normal', 'Normal')], max_length=10),
        ),
        migrations.AddField(
            model_name='emergencyambulancerequest',
            name='rejection_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='emergencyambulancerequest',
            name='urgency_level',
            field=models.CharField(blank=True, choices=[('immediate', 'Immediate'), ('urgent', 'Urgent'), ('standard', 'Standard'), ('non_urgent', 'Non-Urgent')], max_length=15),
        ),
    ]
