# Generated by Django 5.2.3 on 2025-07-05 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IDMSapp', '0005_alter_diseaseanalysis_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptomcheckersession',
            name='session_id',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
