# Generated by Django 5.2.3 on 2025-07-05 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IDMSapp', '0006_alter_symptomcheckersession_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='preventiontip',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='prevention_tips/images/'),
        ),
        migrations.AddField(
            model_name='preventiontip',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='preventiontip',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='prevention_tips/videos/'),
        ),
        migrations.AddField(
            model_name='preventiontip',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
