# Generated by Django 5.2.3 on 2025-07-06 20:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IDMSapp', '0008_remove_preventiontip_disease'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preventiontip',
            options={'ordering': ['priority', 'disease', 'category'], 'verbose_name': 'Disease Prevention Tip', 'verbose_name_plural': 'Disease Prevention Tips'},
        ),
        migrations.RemoveField(
            model_name='preventiontip',
            name='description',
        ),
        migrations.AddField(
            model_name='preventiontip',
            name='content_type',
            field=models.CharField(choices=[('text', 'Text Paragraph'), ('bullet', 'Bullet Points'), ('step', 'Step-by-Step'), ('faq', 'FAQ Format')], default='text', help_text='How the content should be displayed', max_length=20),
        ),
        migrations.AddField(
            model_name='preventiontip',
            name='detailed_content',
            field=models.TextField(default=1, help_text='Main content. Use line breaks for bullets/steps'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preventiontip',
            name='disease',
            field=models.CharField(choices=[('malaria', 'Malaria'), ('pneumonia', 'Pneumonia')], default=1, help_text='Must be either Malaria or Pneumonia', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preventiontip',
            name='prevention_methods',
            field=models.TextField(blank=True, help_text='Specific prevention techniques'),
        ),
        migrations.AddField(
            model_name='preventiontip',
            name='risk_factors',
            field=models.TextField(blank=True, help_text='Key risk factors for this disease'),
        ),
        migrations.AddField(
            model_name='preventiontip',
            name='short_summary',
            field=models.TextField(default=1, help_text='Brief summary for cards/lists (max 350 chars)', max_length=350),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preventiontip',
            name='symptoms',
            field=models.TextField(blank=True, help_text='Common symptoms to watch for'),
        ),
        migrations.AlterField(
            model_name='preventiontip',
            name='category',
            field=models.CharField(choices=[('prevention', 'Prevention'), ('self_care', 'Self Care'), ('when_to_seek_help', 'When to Seek Help'), ('emergency_signs', 'Emergency Signs')], help_text='Type of prevention tip', max_length=20),
        ),
        migrations.AlterField(
            model_name='preventiontip',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional supporting image', null=True, upload_to='prevention_tips/images/'),
        ),
        migrations.AlterField(
            model_name='preventiontip',
            name='priority',
            field=models.IntegerField(default=5, help_text='Display priority (1=highest, 10=lowest)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='preventiontip',
            name='title',
            field=models.CharField(help_text='Short, attention-grabbing title', max_length=200),
        ),
        migrations.AlterField(
            model_name='preventiontip',
            name='video',
            field=models.FileField(blank=True, help_text='Optional instructional video', null=True, upload_to='prevention_tips/videos/'),
        ),
        migrations.AlterField(
            model_name='preventiontip',
            name='video_url',
            field=models.URLField(blank=True, help_text='External video link (YouTube, etc.)', null=True),
        ),
        migrations.AddIndex(
            model_name='preventiontip',
            index=models.Index(fields=['disease', 'category'], name='IDMSapp_pre_disease_6a53a3_idx'),
        ),
        migrations.AddIndex(
            model_name='preventiontip',
            index=models.Index(fields=['priority'], name='IDMSapp_pre_priorit_570dce_idx'),
        ),
    ]
